add tauri example; add install guide
amrbashir/tauri-plugin-vibrancy pull request #32
Opened 2022-04-09 11:30 UTC by awkj

2022-04-09 15:51 UTC, amrbashir requested changes
Adding the tauri example is fine but the installation instructions is not necessary, it is now published to crates.io .

2022-04-09 15:51 UTC, amrbashir commented on README.md
> +window-vibrancy = { git = "https://github.com/tauri-apps/window-vibrancy", branch = "dev" }
The crate is now published, no need to use it from github anymore.

2022-04-09 15:51 UTC, amrbashir commented on examples/tauri.rs
> +}
This example won't compile. Instead, you should include a full tauri project i.e one where `tauri.conf.json` and `Cargo.toml` is present.

2022-05-16 13:51 UTC, doonv commented on examples/tauri.rs
> +      apply_blur(&window, Some((18, 18, 18, 125)))
`window` isn't defined. I'm pretty sure you meant to use `win` right?
```suggestion
      apply_blur(&win, Some((18, 18, 18, 125)))
```

2022-05-16 16:55 UTC, awkj commented on examples/tauri.rs
> +      apply_blur(&window, Some((18, 18, 18, 125)))
Yes, I only have macos, sorry , I forget this PR, wait me , let me fix it and add more code in  example

2022-07-28 11:27 UTC, amrbashir commented
thank you, I have added an example in https://github.com/tauri-apps/window-vibrancy/commit/648bf33d26a6301e6cfcc9bc0c83d8eebe67b18d

2022-07-28 11:27 UTC, closed without merging