Support macOS vibrancy
amrbashir/tauri-plugin-vibrancy pull request #4
Opened 2021-12-23 07:35 UTC by youngsing

Support macOS vibrancy.
Maybe need export a function to let user specify [`NSVisualEffectMaterial`](https://developer.apple.com/documentation/appkit/nsvisualeffectview/material)? 
But now the effect has met my needs.

2021-12-23 08:09 UTC, amrbashir requested changes
I can't thank you enough for this. Just some nitpicks and we are good to go.

2021-12-23 08:09 UTC, amrbashir commented on src/lib.rs
> +        macos::apply_blur(self.ns_window().unwrap() as _);
this should be in a separate function called `apply_vibrancy()`

2021-12-23 08:09 UTC, amrbashir commented on src/lib.rs
> +        macos::apply_blur(self.ns_window() as _);
Same as above

2021-12-23 08:09 UTC, amrbashir commented on src/platform/macos.rs
> +pub fn apply_blur(window: id) {
```suggestion
pub fn apply_vibrancy(window: id, appearance: MacVibrancy) {
```
where `MacVibrancy` is just an export of `NSVisualEffectMaterial` enum under a new name.

2021-12-23 08:09 UTC, amrbashir commented on src/platform/macos.rs
> +            // panic!("Sorry, 'NSVisualEffectView' is only available on macOS 10.10 or newer");
maybe replace this with a debug message instead

2021-12-23 08:28 UTC, amrbashir commented on README.md
> +- `apply_vibrancy()` - **`macOS Only`**, thanks to @youngsing
```suggestion
- `apply_vibrancy()` - **`macOS Only`**, thanks to [@youngsing](https://github.com/youngsing)
```

2021-12-23 09:36 UTC, youngsing commented
I updated the code, maybe you can review it again when you have time. 
Thanks for your guidance.

2021-12-23 20:09 UTC, amrbashir commented
@youngsing I pushed some changes to this PR to only allow the relevant methods on supported platforms, and updated README and docs, can you test if it still works perfectly on macOS before I merge?

2021-12-24 02:40 UTC, youngsing commented
@amrbashir Yeah, it still works on Tao/Tauri windows. See the screenshot at the bottom.
But I got warnings like below:
```
warning: private type `NSVisualEffectState` in public interface (error E0446)
   --> /Users/youngsing/Code/myspace/github.com/tauri-plugin-vibrancy/src/platform/macos.rs:139:5
    |
139 |     unsafe fn setState_(self, state: NSVisualEffectState);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
140 |     unsafe fn setBlendingMode_(self, mode: NSVisualEffectBlendingMode);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(private_in_public)]` on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
```

So we can remove `pub` from `NSVisualEffectView` to fix it? It seems that there is no need to export it.


![Screen Shot 2021-12-24 at 10 06 27](https://user-images.githubusercontent.com/2562374/147307855-2ed34a94-364e-44d2-9582-f861bc0ca8e7.png)
![Screen Shot 2021-12-24 at 10 03 05](https://user-images.githubusercontent.com/2562374/147307862-904f2ff7-13a6-40df-9829-da9eb23bf6d3.png)
.

2021-12-24 02:49 UTC, amrbashir commented
Thanks, merging now.

2021-12-24 02:50 UTC, merged