feat: (macos) add vibrancy state parameter
amrbashir/tauri-plugin-vibrancy pull request #63
Opened 2022-09-15 20:00 UTC by aizcutei

A solution for #59.

2022-09-16 19:55 UTC, amrbashir requested changes
Thanks but we need to make this optional and provide a fallback, make sure to document the default behavior in the function documentation.

Also please add a change file in `.changes` folder with `minor` bump

2022-09-16 19:55 UTC, amrbashir commented on src/lib.rs
> +    #[allow(unused)] state: NSVisualEffectState,
```suggestion
    #[allow(unused)] state: Option<NSVisualEffectState>,
```

2022-09-16 19:55 UTC, amrbashir commented on src/macos.rs
> +            blurred_view.setState_(state);
```suggestion
            blurred_view.setState_(state.unwrap_or(NSVisualEffectState::FollowsWindowActiveState));
```

2022-09-16 19:57 UTC, amrbashir commented on src/macos.rs
> +    pub fn apply_vibrancy(window: id, appearance: NSVisualEffectMaterial, state: NSVisualEffectState) -> Result<(), Error> {
```suggestion
    pub fn apply_vibrancy(window: id, appearance: NSVisualEffectMaterial, state: Option<NSVisualEffectState>) -> Result<(), Error> {
```

2022-09-16 21:04 UTC, aizcutei commented
I updated some codes and added a change file.
Thanks for your guidance.

2022-09-16 21:16 UTC, amrbashir commented on .changes/state_control.md
> +Expose vibrancy state control for macos, default is follow window active state.
Add a 3rd argument to `apply_vibrancy` to specify the vibrancy state, follows the window active state by default.

2022-09-16 21:24 UTC, amrbashir requested changes
also update `examples/tao.rs` and `examples/winit.rs` and run `cargo fmt --all` before commiting

2022-09-16 21:24 UTC, amrbashir commented on .changes/state_control.md
> +Expose vibrancy state control for macos, default is follow window active state.
```suggestion
Add a 3rd argument to `apply_vibrancy()` to control the vibrancy state, follows window active state by default.
```

2022-09-16 21:24 UTC, amrbashir commented on README.md
> +| `apply_vibrancy`                  | macOS 10.10 and newer | `state` is used to control vibrancy state, for default please use `None` and it will follow the window active state. |
revert this change

2022-09-16 21:24 UTC, amrbashir commented on README.md
> +apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, Some(NSVisualEffectState::Active)).expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
```suggestion
apply_vibrancy(&window, NSVisualEffectMaterial::HudWindow, None).expect("Unsupported platform! 'apply_vibrancy' is only supported on macOS");
```

2022-09-16 21:24 UTC, amrbashir commented on README.md
> +use window_vibrancy::{apply_blur, apply_vibrancy, NSVisualEffectMaterial, NSVisualEffectState};
```suggestion
use window_vibrancy::{apply_blur, apply_vibrancy, NSVisualEffectState};
```

2022-09-16 21:24 UTC, amrbashir commented on src/lib.rs
> +//! use window_vibrancy::{apply_vibrancy, apply_blur, NSVisualEffectMaterial, NSVisualEffectState};
```suggestion
//! use window_vibrancy::{apply_vibrancy, apply_blur, NSVisualEffectMaterial};
```

2022-09-16 21:24 UTC, amrbashir commented on src/macos.rs
> +
revert this

2022-09-16 21:24 UTC, amrbashir commented on src/macos.rs
> +            blurred_view.setState_(visual_state);
```suggestion
            blurred_view.setState_(state.unwrap_or(NSVisualEffectState::FollowsWindowActiveState));
```

2022-09-19 12:02 UTC, amrbashir approved these changes
Thank you, I will merge once CI passes

2022-09-19 12:06 UTC, merged